### ISSUE TITLE
Improve mobile UX of the dialog

### ISSUE THREAD

**Issue by pekam** [vaadin/ce-demo#32]
As illustrated in [this figma design](https://www.figma.com/file/s9Q4ozJoA8Z6SRxchAdzAA/Collaboration-Engine?node-id=606%3A1610), on mobile devices the form and chat should be in separate tabs.

[Related discussion in Slack](https://vaadin.slack.com/archives/G013UE9NS15/p1617260209074500).

**Comment by Peppe** [comment]
Done in #36.
